import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

void asyncFileUpload(File file) async{
  var request = http.MultipartRequest("POST", Uri.parse("https://firebasestorage.googleapis.com/v0/b/support-6cf9e.appspot.com/o/${file.path.split("/").last}"));
  var pic = await http.MultipartFile.fromPath("file_field", file.path);
  request.files.add(pic);
  var response = await request.send();
  var responseData = await response.stream.toBytes();
  var responseString = String.fromCharCodes(responseData);
  print(responseString);
}

Future<Autogenerated> loadFiles()async{
  final response = await http.get(
    Uri.parse("https://firebasestorage.googleapis.com/v0/b/support-6cf9e.appspot.com/o"),
  );
  return Autogenerated.fromJson(jsonDecode(response.body));
}

class Autogenerated {
  List<String>? prefixes;
  List<Items>? items;

  Autogenerated({this.prefixes, this.items});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    prefixes = json['prefixes'].cast<String>();
    if (json['items'] != null) {
      items = <Items>[];
      json['items'].forEach((v) {
        items!.add(new Items.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['prefixes'] = this.prefixes;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Items {
  String? name;
  String? bucket;

  Items({this.name, this.bucket});

  Items.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    bucket = json['bucket'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['bucket'] = this.bucket;
    return data;
  }
}